{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please enter ticker for option you want to calculate (e.g. AAPL, AMZN...): AAPL\n",
      "Choose an expiration date and enter it below ('2020-11-27', '2020-12-04', '2020-12-11', '2020-12-18', '2020-12-24', '2020-12-31', '2021-01-15', '2021-02-19', '2021-03-19', '2021-04-16', '2021-06-18', '2021-09-17', '2022-01-21', '2022-06-17', '2022-09-16', '2023-01-20')\n",
      "Enter expiration date (yyyy-mm-dd): 2022-09-16\n",
      "Enter option type (put/call): put\n",
      "Please enter only put or call !\n",
      "Enter option type (put/call): puts\n",
      "Please enter strike: 143\n",
      "we found an option with strike:  145.0\n",
      "we calculated the following price for you:  38.65607352353357\n",
      "This is the traded price 39.45\n",
      "Looks like there is no point in buying/selling this option due to transaction costs.\n"
     ]
    }
   ],
   "source": [
    "# Option Pricing\n",
    "# Evaluating investment opportunities based on the comparison of the intrinsic vs. actually traded values of European options\n",
    "\n",
    "#___________________________________________________________________________________\n",
    "\n",
    "# 1. Preparation\n",
    "\n",
    "# Import libraries and modules\n",
    "import yfinance as yf\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import datetime\n",
    "import math\n",
    "from dateutil.relativedelta import relativedelta\n",
    "\n",
    "#___________________________________________________________________________________\n",
    "\n",
    "# 2. Ask for user inputs\n",
    "\n",
    "#Ask for ticker\n",
    "while True:\n",
    "    ticker = yf.Ticker(input(\"Please enter ticker for option you want to calculate (e.g. AAPL, AMZN...): \"))\n",
    "    if not ticker.options:\n",
    "        print(\"Please enter a correct ticker. You can find them on finance.yahoo.com\")\n",
    "        continue\n",
    "    else:\n",
    "        break\n",
    "#Ask for expiration date\n",
    "while True:    \n",
    "    try:\n",
    "        print(\"Choose an expiration date and enter it below\", ticker.options)\n",
    "        expiration = input(\"Enter expiration date (yyyy-mm-dd): \")\n",
    "        opt = ticker.option_chain(expiration)\n",
    "    except ValueError:\n",
    "        print(\"Please choose a date from the list above. Keep the formatting!\")\n",
    "        continue\n",
    "    else:\n",
    "        break\n",
    "#Ask for type of option and create dataframe with options of that type\n",
    "while True:\n",
    "    try:\n",
    "        opttype = input(\"Enter option type (puts/calls): \")\n",
    "        df = getattr(opt,opttype)\n",
    "    except AttributeError:\n",
    "        print(\"Please enter only puts or calls !\")\n",
    "        continue\n",
    "    else:\n",
    "        break\n",
    "#Ask for strike of option and selecting option closest to user input\n",
    "while True:\n",
    "    try:\n",
    "        option_chosen = df.iloc[(df['strike']-float(input(\"Please enter strike: \"))).abs().argsort()[:1]]\n",
    "    except ValueError:\n",
    "        print(\"please enter a number.\")\n",
    "        continue\n",
    "    else:\n",
    "        break\n",
    "#___________________________________________________________________________________\n",
    "\n",
    "# 3. Get additional data from yahoo finance\n",
    "\n",
    "#Get actual strike, current price and volatility of the chosen option and tell the user what the actual strike is          \n",
    "strike = option_chosen.iloc[0][\"strike\"]\n",
    "price = option_chosen.iloc[0][\"ask\"]\n",
    "volatility = option_chosen.iloc[0][\"impliedVolatility\"]\n",
    "print(\"we found an option with strike: \", strike)\n",
    "\n",
    "\n",
    "#Timedelta for function, time to maturity in years\n",
    "today = datetime.datetime.today()\n",
    "today = today.replace(hour=0, minute=0, second=0, microsecond=0)\n",
    "expiration_datetime = datetime.datetime.strptime(expiration, '%Y-%m-%d')\n",
    "delta= expiration_datetime - today\n",
    "time_to_maturity=delta.days/365\n",
    "    \n",
    "#Stockprice    \n",
    "hist = ticker.history(period=\"max\")\n",
    "hist = hist.tail(1)\n",
    "stockprice = hist.iloc[0][\"Open\"]\n",
    "\n",
    "#risk free rate\n",
    "risk_free = yf.Ticker(\"^IRX\")\n",
    "hist = risk_free.history()\n",
    "hist = hist.tail(1)\n",
    "r = hist.iloc[0][\"Open\"]/100\n",
    "\n",
    "#Dividend approximation based on historic dividend returns. \n",
    "dividend = hist[\"Dividends\"]\n",
    "\n",
    "delta_years_floor = math.floor(time_to_maturity)\n",
    "delta_years_ceil = delta_years_floor + 1\n",
    "prior_year_t = today - relativedelta(years=1)\n",
    "prior_year_expiration = expiration_datetime - relativedelta(years=delta_years_ceil)\n",
    "dividend_approx = sum(dividend.loc[prior_year_t:today])*delta_years_floor\n",
    "dividend_approx = dividend_approx + sum(dividend.loc[prior_year_t:prior_year_expiration])\n",
    "\n",
    "#___________________________________________________________________________________\n",
    "\n",
    "# 4. Definition of four functions for different option types\n",
    "\n",
    "def European_Call_Div (S0, K, T, sigma, n):\n",
    "\n",
    "#Calculation of Initial Parameters\n",
    "  dt = T/n\n",
    "  u = np.exp(sigma*np.sqrt(dt))\n",
    "  d = 1/u\n",
    "  DivRate = dividend_approx / S0\n",
    "  ContAnDivRate = np.log(1+DivRate)\n",
    "  p = (np.exp((r-ContAnDivRate)*dt)-d)/(u-d)\n",
    "\n",
    "# Price tree\n",
    "  # Store the price tree in a square matirx \n",
    "  price_tree = np.zeros([n+1, n+1])\n",
    "\n",
    "  #Calculate the stock price on each note\n",
    "  for i in range (n+1):\n",
    "    for j in range (i+1):\n",
    "      price_tree[j,i] = S0*(d**j)*(u**(i-j))\n",
    "\n",
    "  #Calculate the option value at each node\n",
    "  option = np.zeros([n+1, n+1])\n",
    "  \n",
    "  #Determine the value of the call option at maturity\n",
    "  option[:, n] = np.maximum(np.zeros(n+1), price_tree[:, n]-K)\n",
    "\n",
    "  # Iterate backwards the value of the call option\n",
    "  for i in np.arange(n-1, -1, -1):\n",
    "    for j in np.arange(0,i+1):\n",
    "      option[j, i] = np.exp(-r*dt)*(p*option[j, i+1]+(1-p)*option[j+1, i+1])\n",
    "\n",
    "  # Return\n",
    "  return option[0, 0]\n",
    "\n",
    "def European_Call (S0, K, T, sigma, n):\n",
    "#Calculation of Initial Parameters\n",
    "  dt = T/n\n",
    "  u = np.exp(sigma*np.sqrt(dt))\n",
    "  d = 1/u\n",
    "  p = (np.exp(r*dt)-d)/(u-d)\n",
    "\n",
    "# Price tree\n",
    "  # Store the price tree in a square matirx \n",
    "  price_tree = np.zeros([n+1, n+1])\n",
    "\n",
    "  #Calculate the stock price on each note\n",
    "  for i in range (n+1):\n",
    "    for j in range (i+1):\n",
    "      price_tree[j,i] = S0*(d**j)*(u**(i-j))\n",
    "\n",
    "  #Calculate the option value at each node\n",
    "  option = np.zeros([n+1, n+1])\n",
    "  \n",
    "  #Determine the value of the call option at maturity\n",
    "  option[:, n] = np.maximum(np.zeros(n+1), price_tree[:, n]-K)\n",
    "\n",
    "  # Iterate backwards the value of the call option\n",
    "  for i in np.arange(n-1, -1, -1):\n",
    "    for j in np.arange(0,i+1):\n",
    "      option[j, i] = np.exp(-r*dt)*(p*option[j, i+1]+(1-p)*option[j+1, i+1])\n",
    "\n",
    "  # Return\n",
    "  return option[0, 0]\n",
    "\n",
    "def European_Put_Div (S0, K, T, sigma, n):\n",
    "\n",
    "#Calculation of Initial Parameters\n",
    "  dt = T/n\n",
    "  u = np.exp(sigma*np.sqrt(dt))\n",
    "  d = 1/u\n",
    "  DivRate = dividend_approx / S0\n",
    "  ContAnDivRate = np.log(1+DivRate)\n",
    "  p = (np.exp((r-ContAnDivRate)*dt)-d)/(u-d)\n",
    "\n",
    "# Price tree\n",
    " # Store the price tree in a square matirx \n",
    "  price_tree = np.zeros([n+1, n+1])\n",
    "\n",
    "  #Calculate the stock price on each note\n",
    "  for i in range (n+1):\n",
    "    for j in range (i+1):\n",
    "      price_tree[j,i] = S0*(d**j)*(u**(i-j))\n",
    "\n",
    " #Calculate the option value at each node\n",
    "  option = np.zeros([n+1, n+1])\n",
    "  \n",
    " #Determine the value of the put option at maturity\n",
    "  option[:, n] = np.maximum(np.zeros(n+1), K-price_tree[:, n])\n",
    "\n",
    " # Iterate backwards the value of the put option\n",
    "  for i in np.arange(n-1, -1, -1):\n",
    "    for j in np.arange(0,i+1):\n",
    "      option[j, i] = np.exp(-r*dt)*(p*option[j, i+1]+(1-p)*option[j+1, i+1])\n",
    "\n",
    " # Return\n",
    "  return option[0, 0]\n",
    "\n",
    "def European_Put (S0, K, T, sigma, n):\n",
    "\n",
    "#Calculation of Initial Parameters\n",
    "  dt = T/n\n",
    "  u = np.exp(sigma*np.sqrt(dt))\n",
    "  d = 1/u\n",
    "  p = (np.exp(r*dt)-d)/(u-d)\n",
    "\n",
    "# Price tree\n",
    "  # Store the price tree in a square matirx \n",
    "  price_tree = np.zeros([n+1, n+1])\n",
    "\n",
    "  #Calculate the stock price on each note\n",
    "  for i in range (n+1):\n",
    "    for j in range (i+1):\n",
    "      price_tree[j,i] = S0*(d**j)*(u**(i-j))\n",
    "\n",
    "  #Calculate the option value at each node\n",
    "  option = np.zeros([n+1, n+1])\n",
    "  \n",
    "  #Determine the value of the call option at maturity\n",
    "  option[:, n] = np.maximum(np.zeros(n+1), K-price_tree[:, n])\n",
    "\n",
    "  # Iterate backwards the value of the call option\n",
    "  for i in np.arange(n-1, -1, -1):\n",
    "    for j in np.arange(0,i+1):\n",
    "      option[j, i] = np.exp(-r*dt)*(p*option[j, i+1]+(1-p)*option[j+1, i+1])\n",
    "\n",
    "  # Return\n",
    "  return option[0, 0]\n",
    "\n",
    "#___________________________________________________________________________________\n",
    "\n",
    "# 5. Final calculation\n",
    "#Choosing the correct funtion for the bond and comparing the price to the output of our funtion\n",
    "if opttype == \"call\" and dividend_approx == 0:\n",
    "    pred_price=European_Call(stockprice, strike, time_to_maturity,volatility,50)\n",
    "    print(\"we calculated the following price for you: \",pred_price)\n",
    "    print(\"This is the traded price\",price)\n",
    "elif opttype == \"call\" and dividend_approx > 0:\n",
    "    pred_price=European_Call_Div(stockprice, strike, time_to_maturity,volatility,50)\n",
    "    print(\"we calculated the following price for you: \",pred_price)\n",
    "    print(\"This is the traded price\",price)\n",
    "elif opttype == \"put\" and dividend_approx == 0:\n",
    "    pred_price=European_Put(stockprice, strike, time_to_maturity,volatility,50)\n",
    "    print(\"we calculated the following price for you: \",pred_price)\n",
    "    print(\"This is the traded price\",price)\n",
    "else:\n",
    "    pred_price=European_Put_Div(stockprice, strike, time_to_maturity,volatility,50)\n",
    "    print(\"we calculated the following price for you: \",pred_price)\n",
    "    print(\"This is the traded price\",price)\n",
    "    \n",
    "#Give a recommendation to the user based on the difference in prices\n",
    "pricediff=round(pred_price-price,2)\n",
    "if pricediff>1:\n",
    "    print(\"It looks like you got an investment opportunity here, the calculated price difference is: \",pricediff)\n",
    "elif pricediff<-1:\n",
    "    print(\"We would recommend selling those, the price difference is: \",pricediff)\n",
    "else: \n",
    "    print(\"Looks like there is no point in buying/selling this option due to transaction costs.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
